import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="sticky bottom-0 w-full bg-gray-800 text-white py-4">
          <div className="container mx-auto text-center">
            <Link href="/" className="mx-2 hover:underline">
              Home
            </Link>
            <span className="mx-2">|</span>
            <Link href="/about" className="mx-2 hover:underline">
              About
            </Link>
          </div>
        </footer>
      </body>
    </html>
  );
}
